version: "3"
services:
  graphql-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphql-api
    container_name: graphql-api
    # restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/app

networks:
  default:
    external:
      name: realestate_default # Use the network created by the realEstate app
